steps:
  # Install dependencies
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['install']
    
  # Build the React app
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Deploy to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'build/'
      - 'gs://letz-pocket-website'
    
  # Set public access using iam
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - 'iam'
      - 'ch'
      - 'allUsers:objectViewer'
      - 'gs://letz-pocket-website'

# Configure the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

tags:
  - 'frontend'
  - 'react'
  - 'letz-pocket'
